import {
    ClosePopup,
    Notify,
    QAvatar,
    QBar,
    QBtn,
    QCard,
    QCardActions,
    QCardSection,
    QCarousel,
    QCarouselSlide,
    QChip,
    QDrawer,
    QExpansionItem,
    QFooter,
    QHeader,
    QIcon,
    QImg,
    QInput,
    QIntersection,
    QItem,
    QItemSection,
    QLayout,
    QLinearProgress,
    QList,
    QPage,
    QPageContainer,
    QScrollArea,
    QSeparator,
    QSlideItem,
    QSpace,
    QTab,
    QTable,
    QTabs,
    QTd,
    QTh,
    QToolbar,
    QToolbarTitle,
    QTooltip,
    QTr,
    Quasar,
    Ripple,
} from 'quasar';
import 'quasar/dist/quasar.css';
import '@quasar/extras/material-icons/material-icons.css';

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(Quasar, {
        directives: {
            Ripple, // 显式注册 Ripple 指令
            ClosePopup,
        },
        plugins: {
            Notify,
        },
        config: {
            dark: true, // 全局默认暗黑模式
        },
        components: {
            QAvatar,
            QBtn,
            QBar,
            QCard,
            QChip,
            QCardSection,
            QCardActions,
            QCarousel,
            QCarouselSlide,
            QExpansionItem,
            QDrawer,
            QFooter,
            QHeader,
            QImg,
            QItem,
            QItemSection,
            QIntersection,
            QInput,
            QIcon,
            QLayout,
            QList,
            QLinearProgress,
            QPageContainer,
            QPage,
            QScrollArea,
            QSeparator,
            QSlideItem,
            QSpace,
            QTable,
            QTr,
            QTd,
            QTh,
            QTabs,
            QTab,
            QToolbar,
            QTooltip,
            QToolbarTitle,
        },
    });
});
